### ISSUE TITLE
How to make it to be cracked server??

### ISSUE THREAD

**Issue by AzarinMC** [Google61/mcsw#1]
•help

**Comment by Google61** [comment]
* Start workflow
* After server fully started up, cancel it
* Wait until artifact is uploaded
* Download `server` artifact
* Inside `server.zip`, open `server.properties` file
* Find `online-mode` variable, set it to `false`
* Upload `server.zip` in repo's root
* Run workflow
Boom, server is cracked. Don't forget to remove `server.zip` after first run with it!

**Comment by AzarinMC** [comment]
> * Start workflow
> * After server fully booted, cancel it
> * Wait until artifact is uploaded
> * Download `server` artifact
> * Inside `server.zip`, open `server.properties` file
> * Find `online-mode` variable, set it to `false`
> * Upload `server.zip` in repo's root
> * Run workflow
>   Boom, server is cracked. Don't forget to remove `server.zip` after first run with it!

Thank you 👍🙏
